name: DCenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - pandas=1.5.2
  - numpy>=1.25.*
  - matplotlib=3.8.1
  - seaborn=0.13.0
  - jupyterlab=3.5.0
  - scikit-learn=1.3.2

